## Project 2d

•Implement Feature extraction using PCA with the following data.
•array([[7, 6], [5, 2], [9, 8]])

In [1]:
# Python imports
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [2]:
def cal_PT(A):
    print(A)
    # calculate the mean of each column
    M = mean(A.T, axis=1)
    print(M)
    # center columns by subtracting column means
    C = A - M
    print(C)
    # calculate covariance matrix of centered matrix
    V = cov(C.T)
    print(V)
    # eigendecomposition of covariance matrix
    values, vectors = eig(V)
    print(vectors)
    print(values)
    # project data
    P = vectors.T.dot(C.T)
    return (P.T)   

In [3]:
A = array([[7, 6], [5, 2], [9, 8]])

print(cal_PT(A))

[[7 6]
 [5 2]
 [9 8]]
[7.         5.33333333]
[[ 0.          0.66666667]
 [-2.         -3.33333333]
 [ 2.          2.66666667]]
[[4.         6.        ]
 [6.         9.33333333]]
[[-0.83849224 -0.54491354]
 [ 0.54491354 -0.83849224]]
[ 0.10076147 13.23257187]
[[ 0.36327569 -0.55899483]
 [-0.13939399  3.88480121]
 [-0.2238817  -3.32580638]]
